/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/keyboard.glb");
  const [hovered, setHover] = useState(false)
  const [active, setActive] = useState(false)
  const [gMouseDown, setgMouseDown] = useState(false)
  console.log(hovered)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[0.52, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[1.04, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[1.56, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[0.13, 0, 0.52]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["Material.002"]}
        position={[2.22, 0, 0.52]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={nodes.Plane012.material}
        position={[0.23, 0, 1.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={nodes.Plane013.material}
        position={[0.23, 0, 1.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={nodes.Plane014.material}
        position={[0.78, 0, 1.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={nodes.Plane017.material}
        position={[2.35, 0, 1.04]}
      />
      <mesh
        //base
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.005"]}
        position={[1.16, 0, 0.52]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-6.09, -3.47, -3.39]}
      />
      <mesh
        //discord button
        onPointerOver={() => setHover(true)}
        onPointerOut={() => setHover(false)}
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Material.004"]}
        position={[0.65, 0, 0.52]}
      />
      <mesh
        //github button
        onClick={()=>{
            window.open("https://www.geeksforgeeks.org", "_blank")
            window.focus()
        }}
        onPointerDown={() => setgMouseDown(true)}
        onPointerUp={() => setgMouseDown(false)}
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Material.003"]}
        position={gMouseDown? [1.18, -0.1, 0.55] : [1.18, 0, 0.52]}
      />
      <mesh
        //linked in button
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials["Material.001"]}
        position={[1.7, 0, 0.52]}
      />
    </group>
  );
}

useGLTF.preload("/keyboard.glb");