/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const ref = useRef()
  const { nodes, materials } = useGLTF("/linkedlogo.glb");
  const [hovered, setHover] = useState(false)
  useFrame((state, delta) => (ref.current.rotation.y += hovered? delta : 0))
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        onClick={() => window.open('https://github.com/arnegill')}
        onPointerOver={() => setHover(true)}
        onPointerOut={() => setHover(false)}
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("/linkedlogo.glb");
